name: logevents
on: issues

jobs:
  log:
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: getlog
        run: echo "${{toJSON(github)}}"
